# Generated by Django 3.1.3 on 2020-11-28 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('total', models.IntegerField(blank=True, default='0', null=True)),
                ('add_inventory', models.IntegerField(blank=True, default='0', null=True)),
                ('lead_time', models.IntegerField(blank=True, default='0', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.items')),
            ],
        ),
    ]
