# Generated by Django 3.1.3 on 2020-12-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lead_time', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('no_of_workingdays', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('service_levl', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('standard_deviation', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('carrying_cost', models.PositiveIntegerField(default='0', null=True)),
                ('ordering_cost', models.PositiveIntegerField(default='0', null=True)),
                ('unit_costprice', models.PositiveIntegerField(default='0', null=True)),
                ('yearly_demand', models.PositiveIntegerField(default='0', null=True)),
                ('total_inventory', models.IntegerField(blank=True, default='0', null=True)),
                ('eoq', models.IntegerField(blank=True, default='0', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_quantity', models.IntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('recieve_quantity', models.IntegerField(default='0', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='data.items')),
            ],
        ),
    ]
