# Generated by Django 3.1.3 on 2020-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201128_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
