# Generated by Django 3.1.3 on 2020-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201111_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
