# Generated by Django 3.1.3 on 2020-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201208_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='no_of_workingdays',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
