# Generated by Django 3.1.3 on 2020-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201128_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
