# Generated by Django 3.1.3 on 2020-11-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201128_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='add_inventory',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='lead_time',
        ),
    ]
