# Generated by Django 3.1.3 on 2020-12-08 05:58

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_items_no_of_workingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='z',
            field=models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='carrying_cost',
            field=models.PositiveIntegerField(default='0', help_text='Enter as percentage of unit cost', validators=[data.models.validate_even]),
        ),
    ]
