# Generated by Django 3.1.3 on 2020-12-08 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201208_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='items',
            name='issue_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='recieve_quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
