# Generated by Django 3.1.3 on 2020-11-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201117_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
