# Generated by Django 3.1.3 on 2020-11-20 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20201117_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
