# Generated by Django 3.1.3 on 2020-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_items_rq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='z',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
