# Generated by Django 3.1.3 on 2020-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20201208_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='lt',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
