# Generated by Django 3.1.3 on 2020-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20201120_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='demand',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
