# Generated by Django 3.1.3 on 2020-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_items_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='lt',
        ),
        migrations.AlterField(
            model_name='items',
            name='z',
            field=models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=4, null=True),
        ),
    ]
