# Generated by Django 3.1.3 on 2020-11-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20201122_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
