# Generated by Django 3.1.3 on 2020-12-09 06:15

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_demand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit_costprice',
            field=models.PositiveIntegerField(default='0', null=True, validators=[data.models.validate_zero]),
        ),
    ]
