# Generated by Django 3.1.3 on 2020-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20201122_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='Inventory_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
