# Generated by Django 3.1.3 on 2020-12-09 06:16

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20201209_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='service_level',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, validators=[data.models.validate_even]),
        ),
    ]
